export const BETA_173 = {
  MAX_STEP_UP_BLOCKS: 1,
  SAFE_FALL_HEIGHT_BLOCKS: 3,
  PLAYER_BODY_HEIGHT_BLOCKS: 2,
  POST_ACTION_MAX_HORIZONTAL_SPEED_BLOCKS_PER_TICK: 0.42,
  POST_ACTION_MAX_VERTICAL_ABS_BLOCKS_PER_TICK: 0.52,
} as const;
